#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[245] =
    {   0,
        0,    0,    0,    0,   78,   76,   75,   74,   76,   73,
       76,   62,   76,   64,   64,   64,   63,   65,    6,   65,
       65,    8,   65,   65,   65,   65,   65,    4,    9,    5,
       65,    7,   60,   65,   65,   65,   65,   77,    0,   68,
       73,    0,    0,    0,    0,   64,    0,    0,   71,   69,
       70,    0,    0,   66,   66,   66,    0,   72,   65,   65,
       65,   65,    1,   65,   65,   65,   65,   65,   65,   65,
       65,   65,    2,   65,   42,   65,   65,   40,   65,   65,
       65,   25,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   23,   65,   65,   65,   65,   65,   65,   65,

       65,    3,   67,    0,   71,   70,   69,   64,   12,   13,
       72,    0,   65,   37,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   29,   65,   56,   65,   65,   65,
       65,   15,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   55,   14,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,    0,   65,   65,   65,
       65,   65,   58,   65,   16,   26,   11,   65,   24,   10,
       65,   65,   65,   65,   61,   65,   41,   65,   65,   65,
       35,   65,   31,   65,   65,   65,   65,   44,   43,   27,
       65,   65,   22,   34,   65,   30,   65,   65,   19,   65,

       65,   52,   65,   33,   17,   65,   46,   65,   65,   48,
       50,   38,   65,   45,   65,   49,   51,   65,   57,   65,
       65,   65,   65,   36,   65,   47,   28,   65,   32,   59,
       39,   65,   65,   65,   65,   65,   53,   21,   20,   65,
       54,   65,   18,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   11,   12,
       13,   11,   11,   11,   11,   11,   11,    1,    1,    1,
       14,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   31,   36,   37,   38,   39,
        1,   40,    1,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   31,   59,   60,   61,   62,   31,   63,   64,
       65,   66,    1,   41,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    5,    1,
        6,    6,    6,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    8,
        9,   10,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7
    } ;

static const flex_int16_t yy_base[256] =
    {   0,
        0,    0,    0,    0,  128, 2173, 2173, 2173,  116,    0,
       59,   62,   99,   67,   72,   77, 2173,  106,  145,  193,
      243,  118,  280,  159,   96,  325,  141,  183,  362,  407,
      221,  450,  495,  542,  588,  634,  213, 2173,   93, 2173,
        0,   82,  125,  213,  134,  164,  694,  736,   84,    0,
        0,   80,  151, 2173,   36,   44,  216,    0,  269,  266,
      312,  388,  321,  272,  395,  431,  483,  329,  430,  366,
      500,  480,  427,  536,  490,  492,  552,  554,  280,  589,
      763,  606,  611,  806,  706,  665,  849,  739,  743,  782,
      742,  211,  748,  804,  838,  845,  855,  861,  902,  909,

      852,  907, 2173,  246, 2173,  969,   75,  350, 2173, 2173,
        0,  306,  667,  930,  967, 1022,  954,  960, 1007,  904,
     1027,  963, 1014, 1044, 1025, 1035, 1068, 1081, 1083, 1095,
     1099, 1110, 1130, 1116, 1123, 1133, 1168, 1178, 1154, 1184,
     1175, 1187, 1198, 1218, 1222, 1228, 1231, 1252, 1275, 1282,
     1285, 1292, 1315, 1237, 1271, 1323,  476,  995, 1335, 1360,
     1382, 1382, 1384, 1370, 1382, 1385, 1388, 1435, 1436, 1437,
     1438, 1443, 1481, 1441, 1479, 1482, 1485, 1493, 1497, 1515,
     1527, 1530, 1534, 1551, 1539, 1548, 1570, 1581, 1584, 1587,
     1600, 1603, 1621, 1624, 1638, 1635, 1642, 1679, 1645, 1700,

     1706, 1689, 1706, 1698, 1710, 1721, 1740, 1743, 1736, 1763,
     1769, 1770, 1781, 1792, 1799, 1815, 1817, 1825, 1835, 1842,
     1850, 1854, 1882, 1872, 1764, 1860, 1893, 1903, 1911, 1916,
     1919, 1924, 1967, 1974, 1973, 1979, 1974, 2002, 2026, 2017,
     2025, 2027, 2033, 2173, 2090, 2100, 2110, 2117, 2125, 2131,
     2135, 2145, 2155,   61, 2162
    } ;

static const flex_int16_t yy_def[256] =
    {   0,
      244,    1,  245,  245,  244,  244,  244,  244,  246,  247,
      248,  244,  249,  250,  250,  250,  244,  251,  251,  251,
      251,  251,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   30,   30,   19,   19,  244,  246,  244,
      247,  244,  244,  248,  248,  250,  249,  252,  253,   47,
       47,  253,  244,  244,  244,  244,  244,  254,  255,   19,
       19,  255,   19,   30,  251,  251,  251,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   30,   30,
       30,   30,   30,   19,   19,   19,   19,   19,   19,   84,
       30,   87,   87,   87,   87,   87,   87,   87,   30,   30,

       87,   87,  244,  244,  244,  252,  253,  250,  244,  244,
      254,  244,  255,   87,   87,  255,   87,   87,   87,   30,
       30,   87,   87,   87,   87,   19,   19,   19,   19,   30,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,  244,  255,   30,  255,
      255,   30,   30,   87,   87,   87,   87,   30,   30,   30,
       30,   30,   30,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,  255,   87,  255,

      255,   87,   87,   87,   87,   87,   87,   87,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   87,
       87,  255,  255,   87,   19,   19,   19,   19,   19,   19,
       19,   30,  255,  255,   30,   30,   30,  255,  255,   30,
       30,   30,   30,    0,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244
    } ;

static const flex_int16_t yy_nxt[2240] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,    6,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   25,   32,
       25,   33,   34,   35,   36,   37,   25,   25,   25,    6,
        6,    6,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   25,   32,   33,   34,
       35,   36,   37,   25,   25,   25,   42,  111,  109,   43,
       43,   43,   46,   46,   46,   53,  110,   46,   46,   46,
       53,  107,   46,   46,   46,   53,  107,   46,   46,   46,
      107,   55,   43,   43,   43,  109,   56,   40,   45,   47,

       47,   48,   49,  110,   47,   50,   47,   47,   47,   47,
       47,   47,   47,   57,   58,   60,   59,   59,   59,   55,
       40,   60,   60,   61,   56,   57,   58,  244,   59,   59,
       59,  103,  244,  104,  244,   43,   43,   43,   47,   52,
       47,   42,  244,   60,   43,   43,   43,   62,  244,   60,
       60,   61,   57,   58,   70,   59,   59,   59,  244,   62,
       60,  108,  108,  108,   63,  244,   60,   60,  244,   80,
       64,   65,   53,  244,   46,   46,   46,  244,   60,  244,
      244,   70,  244,  244,   60,   60,   62,  244,   60,  244,
       77,  244,   63,  244,   60,   60,  244,   80,   64,   65,

       57,   58,   60,   59,   59,   59,   60,  244,   60,   60,
      244,  244,   60,   60,   66,  244,  244,   77,  244,  103,
      244,   67,  244,  244,  244,  244,   59,   59,   59,  244,
       60,  244,  102,  244,   62,   86,   60,   60,   60,   60,
       60,  244,   66,   60,  148,   60,   60,   60,  244,   67,
       57,   58,  244,   59,   59,   59,  157,  157,  157,  244,
      102,   68,  244,   86,  244,   69,   60,   60,   60,  244,
       60,  148,   60,  244,   60,   60,   57,  112,  244,   59,
       59,   59,  244,  244,   62,   60,  244,   60,  244,   68,
      244,   60,   60,   69,   71,   60,   60,   72,  244,   73,

      115,  244,   74,  244,   60,   60,   60,  244,  128,  244,
       62,  244,   75,   60,   76,   60,  158,  158,  158,   60,
       60,  244,   71,   60,   60,   72,  244,   73,  115,  114,
       74,   60,   60,   60,   60,  244,  128,   60,   60,   75,
       60,   76,   78,  244,   60,  244,   60,   60,   60,  244,
       60,   60,   79,  244,  119,   60,  244,  114,  244,   60,
      108,  108,  108,  244,  244,   60,   60,  244,   60,  244,
       78,  244,   60,  244,   60,   60,   60,  244,   60,   60,
       79,   60,  119,   60,  121,   60,  244,   60,   60,  244,
       81,   60,   60,  244,   82,   57,  244,  244,   59,   59,

       59,  244,   57,   58,  244,   59,   59,   59,  244,   60,
      244,  244,  121,   60,  244,   60,   60,  244,   81,   60,
       60,   82,   83,  244,  244,  244,   60,  244,  244,   62,
      244,   84,   60,   60,  244,   85,  116,  244,   57,   58,
      244,   59,   59,   59,  244,  244,   60,  244,  244,   60,
       83,  117,   60,   60,   60,   60,   60,  244,  244,   84,
       60,   60,  120,   85,   87,  244,  244,  244,  244,   60,
      244,  244,   62,  244,   60,   60,   60,   60,  244,  117,
       60,   60,  103,   60,   60,   88,  157,  157,  157,  120,
       57,   58,   87,   59,   59,   59,  244,   60,  244,   60,

      244,  244,  123,   60,   60,   60,   60,  244,  244,   60,
      118,   60,   88,   89,   60,   60,   60,  126,   60,   60,
       60,   90,  244,   91,   62,   60,   60,   60,  244,   92,
      123,  244,  122,   60,   60,  244,  244,   60,  118,   60,
      244,   89,   60,   60,   60,  126,   60,   60,   60,   90,
      244,   91,  244,   60,   60,   60,   92,   93,  244,  122,
      244,  124,   60,  244,   94,  244,   60,  244,  244,  125,
       60,   60,  244,   60,  244,   95,  244,   60,   60,   60,
       60,  127,  244,   60,  244,   93,  244,  244,  244,  124,
       60,  244,   94,  244,   60,  244,  125,  244,   60,   60,

      244,   60,   95,   60,   60,   60,   60,   60,   60,  127,
      244,  244,   60,   60,  244,  244,   96,   60,  244,   97,
      244,   60,  244,  129,  244,   98,   60,  244,  244,  244,
       60,   60,   60,  244,   60,   60,  244,  244,  244,   60,
       60,   60,  132,  244,   96,   60,   97,  244,  244,   60,
      129,  244,   98,   60,   60,  244,  244,  244,   60,   60,
       99,  100,   60,   60,  244,  244,  101,   60,  244,  132,
      244,  244,  244,  244,   57,  244,  244,   59,   59,   59,
      244,   60,  244,  244,   60,  244,  244,   60,   99,  100,
       60,  138,  244,  101,   47,   47,   48,   49,  244,   47,

       50,   47,   47,   47,   47,   47,   47,   47,   62,  244,
      244,  244,   60,  244,  244,  244,  244,  244,   60,  138,
      244,  244,  244,  244,  244,   60,  244,  244,  244,  244,
      244,   60,   60,   47,   52,   47,   48,   48,   48,  105,
      137,   48,   48,   48,   48,   48,   48,   48,   48,   48,
      244,  244,  244,   60,  244,  244,  142,   60,   60,   60,
       60,  244,   60,  244,   60,   60,   60,  137,   60,   60,
      147,  244,  143,  244,  244,   48,  244,   48,   60,  244,
       60,   60,   60,  130,  142,   60,   60,   60,  244,  244,
       60,   60,   60,   60,   60,  131,   60,   60,  147,  144,

      143,   60,  145,  244,  244,  244,   60,   60,   60,   60,
      244,  130,  244,  244,  244,   60,  146,  244,  244,   60,
      244,  244,  131,  133,  244,  134,  135,  144,  244,   60,
      145,   60,   60,  244,  244,  244,   60,   60,   60,  244,
      136,  244,  149,  146,  244,  244,  244,  244,  244,  244,
      244,  133,  150,  134,  135,  244,  244,  244,  244,   60,
       60,  244,  244,   60,   60,   60,  244,  136,   60,  149,
       60,   60,   60,  152,   60,   60,  244,   60,   60,  151,
      150,  139,  140,  141,   60,   60,  156,   60,   60,   60,
      153,  244,  244,   60,   60,   60,   60,   60,   60,   60,

      244,  152,   60,   60,   60,   60,  151,  244,  139,  140,
      141,   60,   60,  156,   60,   60,   60,   60,  153,   60,
       60,   60,   60,  244,   60,  244,   60,  244,  165,  244,
      154,  155,   60,   60,  244,  244,  244,   60,  244,   60,
       60,   60,  244,  244,  244,   60,  244,   60,  244,  244,
      244,  244,   60,  244,   60,  244,  165,  244,  154,  155,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   48,
       48,   48,  105,  244,   48,   48,   48,   48,   48,   48,
       48,   48,   48,  159,  244,  162,   60,   60,   60,   60,
       60,   60,   60,  163,   60,   60,  167,   60,  244,   60,

       60,   60,   57,  244,  244,  198,  198,  198,   48,  244,
       48,  159,  162,   60,   60,   60,  244,  244,  244,   60,
      163,   60,   60,  167,   60,  164,   60,   60,   60,   57,
      244,  244,   59,   59,   59,  244,   62,  160,  244,   60,
       60,   60,   60,  166,  161,  244,  168,   60,   60,  244,
      244,   60,  244,  164,   60,   60,  244,   60,   60,   60,
      170,   60,  169,   62,  244,  160,   60,   60,   60,  244,
       60,  166,  161,  168,   60,   60,   60,   60,   60,   60,
      244,  244,   60,   60,   60,   60,   60,   60,  170,   60,
      169,  244,  244,   60,   60,  244,  244,  244,  171,  244,

       60,  244,   60,   60,   60,   60,   60,   60,   60,   60,
       60,  244,  244,  244,  172,   60,  244,  173,  244,   60,
      244,   60,   60,  174,  244,  244,  171,  244,   60,  244,
       60,  175,   60,   60,   60,   60,   60,   60,   60,  244,
      244,  172,   60,   60,   60,  173,  244,   60,  177,   60,
       60,  174,  176,  244,  178,   60,   60,   60,  175,   60,
       60,  244,   60,   60,   60,  179,   60,   60,  244,   60,
       60,   60,  244,  244,  244,  177,   60,   60,  244,  244,
      176,  178,   60,   60,   60,  244,  182,   60,   60,   60,
       60,   60,  179,   60,   60,  180,  181,  244,  244,  244,

       60,   60,   60,  244,  244,  183,  244,  184,   60,   60,
       60,   60,   60,  182,   60,   60,   60,   60,   60,   60,
       60,   60,  244,  180,  181,  244,  244,   60,   60,   60,
       60,   60,   60,  183,  184,   60,   60,   60,   60,   60,
      185,  244,  244,   60,   60,   60,   60,   60,   60,  244,
       60,   60,   60,  186,   60,   60,   60,   60,   60,   60,
      187,   60,   60,   60,  188,   60,  189,  244,  185,   60,
       60,  195,  244,  244,  244,  244,  244,   60,   60,   60,
      186,   60,   60,   60,   60,   60,   60,  187,   60,   60,
       60,  188,   60,  190,  189,  244,   60,   60,  195,  191,

      244,  192,  244,   60,  196,   60,  244,   60,   60,   60,
      193,   60,   60,   60,   60,   60,   60,   60,   60,   60,
      244,  190,  244,  244,   60,   60,   60,  191,  244,  192,
       60,  196,   60,  194,   60,   60,   60,  197,  193,  244,
      244,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,  244,   60,   60,   60,  244,  199,
      244,  194,  244,   60,  244,  197,  244,   57,  244,  244,
       59,   59,   59,  244,   60,   60,   60,  244,   60,  244,
      244,  244,   60,   60,   60,  200,  244,  199,  244,   57,
      244,   60,   59,   59,   59,  244,  244,   60,  244,   60,

      244,   62,   60,  203,   60,  244,   60,  244,   60,  201,
       60,  202,   60,  200,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   62,  244,   60,  244,   60,  244,   60,
      203,   60,  244,  244,   60,  244,   60,  201,   60,  202,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,  244,  244,  205,  244,   60,  204,
       60,   60,   60,   60,   60,   60,   60,   60,  244,  244,
      206,   60,  244,   60,   60,  208,  244,  244,   60,   60,
       60,   60,  244,  244,  205,  244,   60,  204,   60,   60,
       60,   60,   60,   60,   60,   60,   60,  244,  206,   60,

       60,   60,  208,  244,  244,   60,  244,  244,  207,   60,
      244,   60,   60,   60,  209,   60,   60,   60,   60,   60,
      244,  244,  210,  244,   60,   60,   60,   60,  211,   60,
       60,   60,  244,   60,  244,  244,  207,   60,   60,   60,
       60,  209,   60,   60,   60,   60,   60,   60,  212,   60,
      210,  244,   60,   60,   60,  211,   60,   60,   60,   60,
       60,   60,   60,   60,   60,  213,   60,   60,   60,  214,
      244,  215,   60,   60,   60,  212,   60,  216,  244,  244,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,  213,   60,   60,   60,  244,  214,  215,   60,

       60,  217,   60,   60,   60,  216,  244,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,  218,  244,  219,  244,  244,  244,  217,   60,
       60,   60,   60,   60,   60,   60,   60,   60,  244,  244,
       60,   60,   60,   60,   60,   60,   60,   60,   60,  244,
      218,  244,  219,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,  220,  244,   60,   60,   60,
       60,   60,   60,  221,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   57,  112,  244,  198,
      198,  198,  244,  220,   60,   60,   60,   60,   60,   60,

      221,   60,   60,   60,   60,   60,   60,   57,  244,  244,
       59,   59,   59,   57,  244,  244,   59,   59,   59,  244,
       62,   60,   60,   60,  224,  244,  244,  244,  222,  244,
       60,   60,   60,  244,  223,  225,  244,  244,   60,   60,
       60,   62,   60,   60,   60,  244,  244,   62,   60,   60,
       60,   60,  224,   60,   60,   60,  222,   60,   60,   60,
      227,  244,  223,  225,   60,   60,   60,   60,  244,   60,
       60,   60,   60,   60,   60,   60,  226,   60,   60,   60,
       60,   60,   60,   60,   60,   60,  244,   60,  227,  235,
       60,   60,   60,   60,   60,  244,   60,   60,   60,   60,

       60,   60,   60,  226,   60,   60,   60,   60,  244,  228,
      244,   60,   60,   60,   60,   60,   60,  235,   60,   60,
       60,   60,   60,  229,   60,   60,   60,   60,  244,  244,
       60,  244,   60,   60,  244,   60,  244,  228,  244,   60,
       60,   60,   60,   60,   60,   60,  244,  244,   60,   60,
       60,  229,  230,   60,  244,   60,  244,  244,   60,   60,
       60,   57,  244,   60,   59,   59,   59,   60,   60,   60,
      233,   60,  232,   60,   60,  231,   60,   60,   60,   60,
      230,   60,   60,   60,   60,   60,   60,   60,  244,   57,
      244,   60,   59,   59,   59,   62,  244,  244,  233,  234,

      232,   60,  231,   60,   60,   60,   60,   60,  244,   60,
       60,   60,   60,   60,   60,  244,  244,  244,   60,   60,
      244,  244,   60,   62,  244,  244,  244,  234,   60,   60,
       60,   60,   60,   60,  236,   60,   60,   60,   60,   60,
       60,   60,   60,  244,   60,   60,   60,   60,   60,  244,
       60,  244,  237,  244,  244,  244,   60,   60,   60,  244,
      244,  236,  244,   60,   60,   60,   60,   60,  244,   60,
       60,  244,   60,   60,   57,  244,   60,   59,   59,   59,
      237,   57,  244,  244,   59,   59,   59,  244,   60,   60,
      244,  238,  239,  244,   60,  240,  241,   60,   60,  244,

      244,   60,   60,   60,  244,  244,  244,   60,   62,   57,
      244,  244,   59,   59,   59,   62,   60,   60,  244,  238,
      239,  244,   60,  240,  241,   60,   60,  244,  244,   60,
       60,   60,   60,   57,  244,   60,   59,   59,   59,  244,
       60,   60,   60,   62,  242,   60,  244,  243,   60,   60,
      244,   60,  244,   60,  244,   60,  244,   60,  244,  244,
       60,   60,  244,  244,  244,  244,  244,   62,   60,   60,
       60,  244,  242,   60,  244,  243,   60,   60,  244,   60,
      244,   60,  244,   60,  244,   60,  244,  244,  244,   60,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,

       39,  244,   39,   39,   39,   39,   39,   39,   39,   39,
       41,  244,   41,   41,   41,   41,   41,   41,   41,   41,
       44,  244,   44,   44,   44,   51,   51,  244,   51,   51,
       51,   51,   51,   51,   51,   54,   54,   54,   60,   60,
       60,   60,  244,  244,   60,  106,  106,  244,  106,  106,
      106,  106,  106,  244,  106,   52,  244,  244,   52,   52,
       52,   52,   52,   52,   52,  113,  113,  113,  113,  244,
      244,  113,    5,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244
    } ;

static const flex_int16_t yy_chk[2240] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   11,  254,   55,   11,
       11,   11,   12,   12,   12,   14,   56,   14,   14,   14,
       15,  107,   15,   15,   15,   16,   52,   16,   16,   16,
       49,   15,   42,   42,   42,   55,   16,   39,   11,   13,

       13,   13,   13,   56,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   18,   18,   25,   18,   18,   18,   15,
        9,   25,   25,   18,   16,   22,   22,    5,   22,   22,
       22,   43,    0,   43,    0,   43,   43,   43,   13,   13,
       13,   45,    0,   25,   45,   45,   45,   18,    0,   25,
       25,   18,   19,   19,   22,   19,   19,   19,    0,   22,
       27,   53,   53,   53,   19,    0,   27,   27,    0,   27,
       19,   19,   46,   45,   46,   46,   46,    0,   24,    0,
        0,   22,    0,    0,   24,   24,   19,    0,   27,    0,
       24,    0,   19,    0,   27,   27,    0,   27,   19,   19,

       20,   20,   28,   20,   20,   20,   24,    0,   28,   28,
        0,    0,   24,   24,   20,    0,    0,   24,    0,   44,
       44,   20,    0,   44,   44,   44,   57,   57,   57,    0,
       28,    0,   37,    0,   20,   31,   28,   28,   37,   37,
       31,    0,   20,   92,   92,   92,   31,   31,    0,   20,
       21,   21,   44,   21,   21,   21,  104,  104,  104,    0,
       37,   21,    0,   31,    0,   21,   37,   37,   31,    0,
       92,   92,   92,    0,   31,   31,   59,   59,    0,   59,
       59,   59,    0,    0,   21,   60,    0,   64,    0,   21,
        0,   60,   60,   21,   23,   79,   64,   23,    0,   23,

       64,    0,   23,    0,   79,   23,   23,    0,   79,    0,
       59,    0,   23,   60,   23,   64,  112,  112,  112,   60,
       60,    0,   23,   79,   64,   23,    0,   23,   64,   61,
       23,   61,   79,   23,   23,    0,   79,   61,   61,   23,
       63,   23,   26,    0,   26,    0,   63,   63,   68,    0,
       26,   26,   26,    0,   68,   68,    0,   61,  108,   61,
      108,  108,  108,    0,    0,   61,   61,    0,   63,    0,
       26,    0,   26,    0,   63,   63,   68,    0,   26,   26,
       26,   29,   68,   68,   70,   70,    0,   29,   29,    0,
       29,   70,   70,    0,   29,   62,   62,    0,   62,   62,

       62,    0,   65,   65,    0,   65,   65,   65,    0,   29,
        0,    0,   70,   70,    0,   29,   29,    0,   29,   70,
       70,   29,   30,    0,    0,    0,   30,    0,    0,   62,
        0,   30,   30,   30,    0,   30,   65,    0,   66,   66,
        0,   66,   66,   66,    0,    0,   73,    0,    0,   69,
       30,   66,   73,   73,   30,   69,   69,    0,    0,   30,
       30,   30,   69,   30,   32,    0,    0,    0,    0,   32,
        0,    0,   66,    0,   73,   32,   32,   69,    0,   66,
       73,   73,  157,   69,   69,   32,  157,  157,  157,   69,
       67,   67,   32,   67,   67,   67,    0,   32,    0,   72,

        0,    0,   72,   32,   32,   72,   72,    0,    0,   75,
       67,   76,   32,   33,   33,   75,   75,   76,   76,   71,
       33,   33,    0,   33,   67,   71,   71,   72,    0,   33,
       72,    0,   71,   72,   72,    0,    0,   75,   67,   76,
        0,   33,   33,   75,   75,   76,   76,   71,   33,   33,
        0,   33,    0,   71,   71,   74,   33,   34,    0,   71,
        0,   74,   74,    0,   34,    0,   34,    0,    0,   74,
       34,   77,    0,   78,    0,   34,    0,   77,   77,   78,
       78,   77,    0,   74,    0,   34,    0,    0,    0,   74,
       74,    0,   34,    0,   34,    0,   74,    0,   34,   77,

        0,   78,   34,   35,   80,   77,   77,   78,   78,   77,
        0,    0,   35,   80,    0,    0,   35,   80,    0,   35,
        0,   82,    0,   80,    0,   35,   83,    0,    0,    0,
       82,   35,   80,    0,   82,   83,    0,    0,    0,   83,
       35,   80,   83,    0,   35,   80,   35,    0,    0,   82,
       80,    0,   35,   36,   83,    0,    0,    0,   82,   36,
       36,   36,   82,   83,    0,    0,   36,   83,    0,   83,
        0,    0,    0,    0,  113,  113,    0,  113,  113,  113,
        0,   36,    0,    0,   86,    0,    0,   36,   36,   36,
       86,   86,    0,   36,   47,   47,   47,   47,    0,   47,

       47,   47,   47,   47,   47,   47,   47,   47,  113,    0,
        0,    0,   86,    0,    0,    0,    0,    0,   86,   86,
        0,    0,    0,    0,    0,   85,    0,    0,    0,    0,
        0,   85,   85,   47,   47,   47,   48,   48,   48,   48,
       85,   48,   48,   48,   48,   48,   48,   48,   48,   48,
        0,    0,    0,   85,    0,    0,   88,   91,   88,   85,
       85,    0,   89,    0,   88,   88,   91,   85,   89,   89,
       91,    0,   89,    0,    0,   48,    0,   48,   81,    0,
       93,   93,   93,   81,   88,   91,   88,   81,    0,    0,
       89,   81,   88,   88,   91,   81,   89,   89,   91,   90,

       89,   90,   90,    0,    0,    0,   81,   93,   93,   93,
        0,   81,    0,    0,    0,   81,   90,    0,    0,   81,
        0,    0,   81,   84,    0,   84,   84,   90,    0,   90,
       90,   84,   84,    0,    0,    0,   94,   94,   94,    0,
       84,    0,   94,   90,    0,    0,    0,    0,    0,    0,
        0,   84,   95,   84,   84,    0,    0,    0,    0,   84,
       84,    0,    0,   94,   94,   94,    0,   84,   87,   94,
       95,   95,   95,   97,   87,   87,    0,   96,   96,   96,
       95,   87,   87,   87,  101,  101,  101,   97,   97,   97,
       98,    0,    0,   98,   98,   98,   87,   95,   95,   95,

        0,   97,   87,   87,   96,   96,   96,    0,   87,   87,
       87,  101,  101,  101,   97,   97,   97,   99,   98,  120,
       98,   98,   98,    0,  100,    0,   99,    0,  120,    0,
       99,  100,  120,  100,    0,    0,    0,  100,    0,  102,
      102,  102,    0,    0,    0,   99,    0,  120,    0,    0,
        0,    0,  100,    0,   99,    0,  120,    0,   99,  100,
      120,  100,  114,  114,  114,  100,  102,  102,  102,  106,
      106,  106,  106,    0,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  115,    0,  117,  117,  117,  117,  114,
      114,  114,  118,  118,  118,  122,  122,  122,    0,  115,

      115,  115,  158,  158,    0,  158,  158,  158,  106,    0,
      106,  115,  117,  117,  117,  117,    0,    0,    0,  118,
      118,  118,  122,  122,  122,  119,  115,  115,  115,  116,
      116,    0,  116,  116,  116,    0,  158,  116,    0,  119,
      119,  119,  121,  121,  116,    0,  123,  123,  123,    0,
        0,  121,    0,  119,  126,  121,    0,  125,  125,  125,
      126,  126,  124,  116,    0,  116,  119,  119,  119,    0,
      121,  121,  116,  123,  123,  123,  124,  124,  124,  121,
        0,    0,  126,  121,  125,  125,  125,  127,  126,  126,
      124,    0,    0,  127,  127,    0,    0,    0,  128,    0,

      128,    0,  129,  124,  124,  124,  128,  128,  129,  129,
      130,    0,    0,    0,  129,  127,    0,  130,    0,  130,
        0,  127,  127,  130,    0,    0,  128,    0,  128,    0,
      129,  131,  131,  131,  128,  128,  129,  129,  130,    0,
        0,  129,  132,  132,  132,  130,    0,  130,  134,  134,
      134,  130,  133,    0,  135,  135,  135,  135,  131,  131,
      131,    0,  133,  133,  133,  136,  136,  136,    0,  132,
      132,  132,    0,    0,    0,  134,  134,  134,    0,    0,
      133,  135,  135,  135,  135,    0,  139,  139,  139,  133,
      133,  133,  136,  136,  136,  137,  138,    0,    0,    0,

      137,  137,  137,    0,    0,  140,    0,  141,  141,  141,
      138,  138,  138,  139,  139,  139,  140,  140,  140,  142,
      142,  142,    0,  137,  138,    0,    0,  137,  137,  137,
      143,  143,  143,  140,  141,  141,  141,  138,  138,  138,
      144,    0,    0,  140,  140,  140,  142,  142,  142,    0,
      144,  144,  144,  145,  145,  145,  145,  143,  143,  143,
      146,  146,  146,  147,  147,  147,  148,    0,  144,  154,
      154,  154,    0,    0,    0,    0,    0,  144,  144,  144,
      145,  145,  145,  145,  148,  148,  148,  146,  146,  146,
      147,  147,  147,  149,  148,    0,  154,  154,  154,  150,

        0,  151,    0,  155,  155,  155,    0,  149,  149,  149,
      152,  148,  148,  148,  150,  150,  150,  151,  151,  151,
        0,  149,    0,    0,  152,  152,  152,  150,    0,  151,
      155,  155,  155,  153,  149,  149,  149,  156,  152,    0,
        0,  150,  150,  150,  151,  151,  151,  153,  153,  153,
      159,  152,  152,  152,    0,  156,  156,  156,    0,  159,
        0,  153,    0,  159,    0,  156,    0,  160,  160,    0,
      160,  160,  160,    0,  153,  153,  153,    0,  159,    0,
        0,    0,  156,  156,  156,  160,    0,  159,    0,  161,
      161,  159,  161,  161,  161,    0,    0,  162,    0,  163,

        0,  160,  164,  164,  164,    0,  162,    0,  163,  161,
      162,  162,  163,  160,  165,  165,  165,  166,  166,  166,
      167,  167,  167,  161,    0,  162,    0,  163,    0,  164,
      164,  164,    0,    0,  162,    0,  163,  161,  162,  162,
      163,  165,  165,  165,  166,  166,  166,  167,  167,  167,
      168,  169,  170,  171,    0,    0,  171,    0,  172,  168,
      169,  170,  171,  168,  169,  170,  171,  172,    0,    0,
      172,  172,    0,  174,  174,  174,    0,    0,  168,  169,
      170,  171,    0,    0,  171,    0,  172,  168,  169,  170,
      171,  168,  169,  170,  171,  172,  173,    0,  172,  172,

      174,  174,  174,    0,    0,  173,    0,    0,  173,  173,
        0,  175,  175,  175,  176,  176,  176,  177,  177,  177,
        0,    0,  178,    0,  173,  178,  178,  178,  179,  179,
      179,  179,    0,  173,    0,    0,  173,  173,  175,  175,
      175,  176,  176,  176,  177,  177,  177,  180,  180,  180,
      178,    0,  178,  178,  178,  179,  179,  179,  179,  181,
      181,  181,  182,  182,  182,  182,  183,  183,  183,  184,
        0,  185,  185,  185,  180,  180,  180,  186,    0,    0,
      186,  186,  186,  184,  184,  184,  181,  181,  181,  182,
      182,  182,  182,  183,  183,  183,    0,  184,  185,  185,

      185,  187,  187,  187,  187,  186,    0,  186,  186,  186,
      184,  184,  184,  188,  188,  188,  189,  189,  189,  190,
      190,  190,  191,    0,  192,    0,    0,    0,  187,  187,
      187,  187,  191,  191,  191,  192,  192,  192,    0,    0,
      188,  188,  188,  189,  189,  189,  190,  190,  190,    0,
      191,    0,  192,  193,  193,  193,  194,  194,  194,  191,
      191,  191,  192,  192,  192,  195,    0,  196,  196,  196,
      195,  195,  195,  197,  197,  197,  197,  199,  199,  199,
      193,  193,  193,  194,  194,  194,  198,  198,    0,  198,
      198,  198,    0,  195,  196,  196,  196,  195,  195,  195,

      197,  197,  197,  197,  199,  199,  199,  200,  200,    0,
      200,  200,  200,  201,  201,    0,  201,  201,  201,    0,
      198,  202,  202,  202,  203,    0,    0,    0,  200,    0,
      204,  204,  204,    0,  201,  206,    0,    0,  203,  203,
      203,  200,  205,  205,  205,    0,    0,  201,  202,  202,
      202,  209,  203,  206,  206,  206,  200,  204,  204,  204,
      209,    0,  201,  206,  209,  203,  203,  203,    0,  205,
      205,  205,  207,  207,  207,  208,  208,  208,  210,  209,
      206,  206,  206,  225,  211,  212,    0,  210,  209,  225,
      225,  210,  209,  211,  212,    0,  213,  211,  212,  207,

      207,  207,  208,  208,  208,  213,  210,  214,    0,  213,
        0,  225,  211,  212,  215,  210,  214,  225,  225,  210,
      214,  211,  212,  215,  213,  211,  212,  215,    0,    0,
      216,    0,  217,  213,    0,  214,    0,  213,    0,  216,
      218,  217,  215,  216,  214,  217,    0,    0,  214,  218,
      219,  215,  218,  218,    0,  215,    0,    0,  216,  219,
      217,  222,  222,  219,  222,  222,  222,  216,  218,  217,
      222,  216,  221,  217,  220,  220,  220,  218,  219,  226,
      218,  218,  221,  221,  221,  226,  226,  219,    0,  223,
      223,  219,  223,  223,  223,  222,    0,    0,  222,  223,

      221,  220,  220,  220,  224,  224,  224,  226,    0,  221,
      221,  221,  227,  226,  226,    0,    0,    0,  227,  227,
        0,    0,  228,  223,    0,    0,    0,  223,  228,  228,
      229,  224,  224,  224,  228,  230,  229,  229,  231,  232,
      227,  230,  230,    0,  231,  231,  227,  227,  232,    0,
      228,    0,  232,    0,    0,    0,  228,  228,  229,    0,
        0,  228,    0,  230,  229,  229,  231,  232,    0,  230,
      230,    0,  231,  231,  233,  233,  232,  233,  233,  233,
      232,  234,  234,    0,  234,  234,  234,    0,  235,  237,
        0,  233,  234,    0,  236,  235,  236,  235,  237,    0,

        0,  235,  237,  236,    0,    0,    0,  236,  233,  238,
      238,    0,  238,  238,  238,  234,  235,  237,    0,  233,
      234,    0,  236,  235,  236,  235,  237,    0,    0,  235,
      237,  236,  240,  239,  239,  236,  239,  239,  239,    0,
      241,  240,  242,  238,  240,  240,    0,  242,  243,  241,
        0,  242,    0,  241,    0,  242,    0,  243,    0,    0,
      240,  243,    0,    0,    0,    0,    0,  239,  241,  240,
      242,    0,  240,  240,    0,  242,  243,  241,    0,  242,
        0,  241,    0,  242,    0,  243,    0,    0,    0,  243,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      246,    0,  246,  246,  246,  246,  246,  246,  246,  246,
      247,    0,  247,  247,  247,  247,  247,  247,  247,  247,
      248,    0,  248,  248,  248,  249,  249,    0,  249,  249,
      249,  249,  249,  249,  249,  250,  250,  250,  251,  251,
      251,  251,    0,    0,  251,  252,  252,    0,  252,  252,
      252,  252,  252,    0,  252,  253,    0,    0,  253,  253,
      253,  253,  253,  253,  253,  255,  255,  255,  255,    0,
        0,  255,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[78] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 5 "lexico.l"
#include <iostream>
#include <QString>
#include "parser.h"
#include <stdio.h>
#include <string>
#include <QList>

    int yylex();
    void yyerror(const char *s);

#line 1057 "scanner.cpp"

#line 1059 "scanner.cpp"

#define INITIAL 0
#define COM 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 45 "lexico.l"


#line 1278 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 245 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2173 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "lexico.l"
{strcpy(yylval.TEXT, "BF");return Tbf;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "lexico.l"
{strcpy(yylval.TEXT, "FF");return Tff;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "lexico.l"
{strcpy(yylval.TEXT, "WF");return Twf;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "lexico.l"
{strcpy(yylval.TEXT, "K");return Tk;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "lexico.l"
{strcpy(yylval.TEXT, "M");return Tm;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "lexico.l"
{strcpy(yylval.TEXT, "B");return Tb;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "lexico.l"
{strcpy(yylval.TEXT, "P");return Tp;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "lexico.l"
{strcpy(yylval.TEXT, "E");return Te;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "lexico.l"
{strcpy(yylval.TEXT, "L");return Tl;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "lexico.l"
{strcpy(yylval.TEXT, "FULL");return Tfull;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "lexico.l"
{strcpy(yylval.TEXT, "FAST");return Tfast;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "lexico.l"
{strcpy(yylval.TEXT, "2FS");return T2fs;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "lexico.l"
{strcpy(yylval.TEXT, "3FS");return T3fs;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Trep;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "lexico.l"
{strcpy(yylval.TEXT, "MBR");return Tmbr;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "lexico.l"
{strcpy(yylval.TEXT, "DISK");return Tdisk;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "lexico.l"
{strcpy(yylval.TEXT, "INODE");return Tinode;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "lexico.l"
{strcpy(yylval.TEXT, "JOURNALING");return Tjournaling;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "lexico.l"
{strcpy(yylval.TEXT, "BLOCK");return Tblock;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "lexico.l"
{strcpy(yylval.TEXT, "BM_INODE");return Tbminode;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "lexico.l"
{strcpy(yylval.TEXT, "BM_BLOCK");return Tbmblock;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "lexico.l"
{strcpy(yylval.TEXT, "TREE");return Ttree;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "lexico.l"
{strcpy(yylval.TEXT, "SB");return Tsb;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "lexico.l"
{strcpy(yylval.TEXT, "FILE");return Tfile;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "lexico.l"
{strcpy(yylval.TEXT, "LS");return Tls;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Texec;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 82 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tsize;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 83 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tmkdisk;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 84 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tf;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tu;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tpath;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Trmdisk;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tfdisk;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Ttype;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tname;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tdelete;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tadd;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tmount;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tumount;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 95 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tid;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tmkfs;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tfs;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Truta;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 99 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Troot;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 101 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tpause;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tlogin;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 105 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tlogout;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 106 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tmkgrp;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 107 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Trmgrp;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 108 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tmkusr;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 109 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Trmusr;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tchgrp;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 112 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tuser;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tpwd;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 114 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tpwd;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 115 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tgrp;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 117 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Ttouch;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 118 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tcont;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 119 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tstdin;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 120 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tr;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 122 "lexico.l"
{strcpy(yylval.TEXT, yytext);return Tloss;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 124 "lexico.l"
{strcpy(yylval.TEXT, yytext);return guion;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 125 "lexico.l"
{strcpy(yylval.TEXT, yytext);return igual;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 128 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return num;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 129 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return identificador;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return ide2;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return caracter;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return cadena;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return cadena2;}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 134 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return cadena3;}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 135 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return cadena4;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 136 "lexico.l"
{ strcpy(yylval.TEXT, yytext);return cadena5;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "lexico.l"
{}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 142 "lexico.l"
{}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "lexico.l"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 147 "lexico.l"
{

std::cout<<"Error Lexico \n";
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 "lexico.l"
ECHO;
	YY_BREAK
#line 1736 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 245 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 245 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 244);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 151 "lexico.l"
